In [1]:
import import_ipynb
from imports.imports_common_preprocessing import *
from load_dataset_RGB import *

importing Jupyter notebook from c:\Users\joao.correia\Documents\Faculdade\Monografia_Joao_Victor_A_Correia\imports\imports_common_preprocessing.ipynb
importing Jupyter notebook from load_dataset_RGB.ipynb
importing Jupyter notebook from c:\Users\joao.correia\Documents\Faculdade\Monografia_Joao_Victor_A_Correia\imports\imports_common.ipynb


### 3. Particionamento dos dados em conjunto de treino e em conjunto de teste.

In [12]:
# Divide os dados em conjuntos de treinamento, teste e validação
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = TEST_SIZE, random_state = SEED, stratify = y)
X_test, X_val, y_test, y_val = train_test_split(X_test, y_test, test_size = VAL_SIZE, random_state = SEED, stratify = y_test)

validation_data = (X_val, y_val)

x_shape = X.shape[0]
X_train_shape = X_train.shape[0]
X_test_shape = X_test.shape[0]
X_val_shape = X_val.shape[0]

print("X: ", x_shape)
print("X_train: ", X_train_shape)
print("X_test: ", X_test_shape)
print("X_val: ", X_val_shape)

X:  6400
X_train:  4480
X_test:  1280
X_val:  640


In [13]:
# Normaliza os valores de pixel para que estejam entre 0 e 1
X_train = np.array(X_train) / 255.0
X_test = np.array(X_test) / 255.0
X_val = np.array(X_val) / 255.0

# Converte os rótulos em valores numéricos usando LabelEncoder
label_encoder = LabelEncoder()
print(np.unique(y_train, return_counts = True))
y_train = label_encoder.fit_transform(y_train)
print(np.unique(y_train, return_counts = True))
print(np.unique(y_test, return_counts = True))
y_test = label_encoder.transform(y_test)
print(np.unique(y_test, return_counts = True))
y_val = label_encoder.transform(y_val)
print(np.unique(y_test, return_counts = True))

# Transforma as imagens em vetores de recursos
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)
y_val_categorical = to_categorical(y_val)


dataset_validation_categorical = (X_val, y_val_categorical)
dataset_validation = (X_val, y_val)

# Transforma as imagens em vetores de recursos
X_train_flatten = [(np.array(img)).flatten() for img in X_train]
X_test_flatten = [(np.array(img)).flatten() for img in X_test]
X_val_flatten = [(np.array(img)).flatten() for img in X_val]

(array(['Mild_Demented', 'Moderate_Demented', 'Non_Demented',
       'Very_Mild_Demented'], dtype='<U18'), array([ 627,   45, 2240, 1568], dtype=int64))
(array([0, 1, 2, 3], dtype=int64), array([ 627,   45, 2240, 1568], dtype=int64))
(array(['Mild_Demented', 'Moderate_Demented', 'Non_Demented',
       'Very_Mild_Demented'], dtype='<U18'), array([179,  13, 640, 448], dtype=int64))
(array([0, 1, 2, 3]), array([179,  13, 640, 448], dtype=int64))
(array([0, 1, 2, 3]), array([179,  13, 640, 448], dtype=int64))


In [14]:
unique, frequency = np.unique(y_train, return_counts = True) 
print("Unique Values:", unique) 
print("Frequency Values:", frequency)

Unique Values: [0 1 2 3]
Frequency Values: [ 627   45 2240 1568]


In [ ]:
target_names = label_encoder.classes_